### ISSUE TITLE
Using compose on multi-line documents results in: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by Claudiu** [fmpwizard/go-quilljs-delta#5]
First of all, thank you for creating this library, it saved me quite a few hours. I'm having a few problems with composing deltas, mainly with multi-line documents.

Steps to reproduce:

**Given the original delta:**
`{"ops":[{"insert":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tempus ex at hendrerit pretium. Sed feugiat tempus leo, eu placerat nibh ullamcorper id. In non vulputate sapien. Suspendisse laoreet ultricies elementum. Aliquam magna augue, varius id massa in, sagittis placerat velit. Vestibulum ut mi a erat congue feugiat. Donec sed mauris sed lacus feugiat fermentum. Etiam molestie convallis lorem eget venenatis. Curabitur imperdiet ante maximus eleifend convallis. In fermentum sem a bibendum auctor. Vivamus pharetra quis nibh sed accumsan. Aliquam gravida, justo eget accumsan semper, ex elit sagittis enim, ut consectetur magna est at justo."},{"insert":"\n","attributes":{"align":"justify"}},{"insert":"Quisque sagittis, magna at semper euismod, erat ex viverra velit, a hendrerit augue felis vel nulla. In porta leo ac arcu pharetra, et cursus sapien feugiat. Cras sed facilisis tellus. Vivamus hendrerit posuere condimentum. Curabitur laoreet enim quam, eget porta sem pharetra ut. In eleifend lorem a nulla pulvinar, eu mollis dolor sodales. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas."},{"insert":"\n","attributes":{"align":"justify"}},{"insert":"\n"}]}`

**The _patch_**
`{"ops":[{"retain":872},{"insert":"s"}]}`

Running `original.Compose(patch)` results in `runtime error: slice bounds out of range`

`
test/vendor/github.com/fmpwizard/go-quilljs-delta/delta.(*Iterator).Next(0xc4205e1180, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/claudiu/go/src/test/vendor/github.com/fmpwizard/go-quilljs-delta/delta/iterator.go:69 +0x2f9
test/vendor/github.com/fmpwizard/go-quilljs-delta/delta.(*Delta).Compose(0xc42011ca60, 0xc4208fa180, 0x2, 0x4, 0xc42011cbe0)
        /home/claudiu/go/src/test/vendor/github.com/fmpwizard/go-quilljs-delta/delta/delta.go:216 +0x5f5
`

LE: I'm trying to mimic the functionality of updateContents in Quill. The two deltas were the result of this:

``` javascript
quill.on('text-change', (delta, oldDelta, source) => {
   console.log(JSON.stringify(delta), JSON.stringify(oldDelta));
})
```

**Comment by fmpwizard** [comment]
I just saw this ticket, I'll take a look at it later tonight or tomorrow and get back to you.

**Comment by fmpwizard** [comment]
Hi @Claudiu 

I added a unit test

https://github.com/fmpwizard/go-quilljs-delta/blob/diego_issue_5/delta/delta_test.go#L1076

but it doesn't trigger the bug you describe. Could you check if I missed something from your original test case?

The test fails on purpose, to see what the library is doing, the output I get is

```
    /home/diego/work/golang/src/github.com/fmpwizard/go-quilljs-delta/delta/delta_test.go:1094: boom1 5
    /home/diego/work/golang/src/github.com/fmpwizard/go-quilljs-delta/delta/delta_test.go:1101: boom3 Quisque sagittis, magna at semper euismod, erat ex viverra velit, a hendrerit augue felis vel nulla. In porta leo ac arcu pharetra, et cursus sapien feugiat. Cras sed facilisis tellus. Vivamus hendrerit posuere condimentum bug not happening . Curabitur laoreet enim quam, eget porta sem pharetra ut. In eleifend lorem a nulla pulvinar, eu mollis dolor sodales. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
```


Note that instead of only adding a single `s` to trigger the bug, I added 3 words, to make it easier to find in the text `bug not happening`.

**Comment by fmpwizard** [comment]
feel free to reopen or enter a new ticket if you run into this, but I couldn't reproduce it
