### ISSUE TITLE
tests failing.

### ISSUE THREAD

**Issue by gedw99** [fmpwizard/go-quilljs-delta#7]
line 661 and 669 of delta_test.go

**Comment by gedw99** [comment]
just do: go test ./...

I see that the failures on 661 & 669 and causing all tests to not run.

**Comment by fmpwizard** [comment]
I'll check later tonight, thanks!

**Comment by fmpwizard** [comment]
Thanks, I hadn't run this project with the new go version that runs go vet on test files, thanks, the fix is pushed to master
